### PR TITLE
In order to fix #30

### LINKED ISSUE #30: Should not force sslversion.
SSLv3 is deprecated, and actually removed in Ubuntu 16.04 LTS+PHP 7. We shouldn't force cURL in using any particular version.

### PR DESCRIPTION
**Pull request by mevdschee**
It is probably better to not have these settings in there by default as they are insecure and cause problems.

### CODE REVIEW

**Comment by GabrielAnca** [comment]
Hi Maurits! 

We had some issues in other bundles due to the same setting, and this definitely fixed it. I will merge it when I arrive to the office and I will check if there are other bundles that still have the same issue. 

Thanks!

**Comment by mevdschee** [comment]
Great! Please ensure that you release as well (under "releases" in Github) otherwise people with composer will not benefit. Thank you.

**Comment by GabrielAnca** [comment]
Hi @mevdschee I have created a new release including your bugfix. Thanks a lot to you and @sam0737 for the contribution! 😄

**Comment by mevdschee** [comment]
Thank you @GabrielAnca

**Pull request merged**
